### ISSUE TITLE
verification high temperature incorrect

### ISSUE THREAD

**Issue by joejoezz** [jweyn/theta-e#19]
The new 6-hourly data parsing in /verify/verification.py is not pulling the correct high temperature for the previous day. It probably works when run on an hourly crontab but in my tests I usually run once per day in the afternoon (for KYKM) and it isn't pulling the correct high temperature.

I'm trying to figure out what's going on :)

**Comment by joejoezz** [comment]
Ok what I think is happening is that the getVerification service runs verify/obs.py (updates hourly obs) before verify/getVerification.py (updates daily obs). So when db/get_latest_date is run the second time it thinks that we are already up to date based on hourly obs. So it can potentially miss the last 6-hour forecast if one hasn't run the theta-e script since the previous day. 

I think the way to fix this is to write a new function in db.py to query the KYKM_VERIF table rather than KYKM_OBS in order to find the last date with a daily forecast that can be called in verification.py to replace db/get_latest_date.

Do you think that is right @jweyn???

**Comment by jweyn** [comment]
Ah, I thought I'd been careful enough with those checks, but I think you're right, it must be "seeing" the newly updated obs and therefore not going back far enough to fix the previous day. I suppose the easiest way is to check the latest verification date. It might not actually even use more MesoWest units. I'll take a look and push an update.

**Comment by joejoezz** [comment]
I think it can be fixed in only one line in verification.py:
first_date = get_latest_date(config, 'forecast', stid, 'VERIF')

**Comment by jweyn** [comment]
Yep, just added a check if get_latets_date fails. Check to see if it works now!

**Comment by joejoezz** [comment]
That should do the trick!
